version: "2.5"

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - ./.env
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html
    restart: on-failure
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - ./.env
    networks:
      - inception
    expose:
      - "3306"
    # volumes:
    #   - db_volume:/var/lib/mysql
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - ./.env
    networks:
      - inception
    expose:
      - "9000"
    depends_on:
      - mariadb
    # volumes:
    #   - wp_volume:/var/www/html
    restart: on-failure

volumes:
  wp_volume:
    driver_opts:
      type: none
      device: ~/WordPress/
      o: bind
#   db_volume:
#     driver_opts:
#       type: none
#       device: ~/Mariadb/
#       o: bind

networks:
  inception: