FROM debian:bullseye

RUN apt update \
    && apt install nginx openssl curl -y \
        && openssl req -new -x509 -nodes \
        -subj "/CN=localhost" -newkey rsa:2048 \
        -keyout /etc/ssl/private/private_key_file \
        -out /etc/ssl/certs/certificate_file

COPY conf/nginx.conf /etc/nginx/nginx.conf

CMD [ "nginx", "-g", "daemon off;" ]